### ISSUE TITLE
using file system

### ISSUE THREAD

**Issue by Alakazam03** [arnaucube/merkletree-rs#2]
I have set value false while inititaing db. I am trying to call the same "test" to operate over created merkle tree. But i am not able to acess the old data in another function again.

`
pub fn check_user_pref(message_block : Json<MessageBlock>) -> String {
    let message_block : MessageBlock = message_block.into_inner();
    {
        let mut sto = db::Db::new("test".to_string(), false);
        let mut mt = MerkleTree::new(&mut sto, 140 as u32);

        let phone_number_t : String = "9034218121".to_string();   
      
        let val: TestValue = TestValue {
            bytes: phone_number_t.as_bytes().to_vec(),
            index_length: 10,
        };

        mt.add(&val).unwrap();
        println!("{:?}", mt.get_root());

        let mp = mt.generate_proof(val.hi());
        println!("{:?}", mp);

       
    }

`
`
pub fn generate_proof() {
    let mut sto = db::Db::new("test2".to_string(), false);
    let mut mt = MerkleTree::new(&mut sto, 140);
    let phone_number_t : String = "9034218121".
    let val: TestValue = TestValue {
            bytes: phone_number_t.as_bytes().to_vec(),
            index_length: 10,
        };
   println!("{}", mt.get_root());
}
`

I am getting mt.get_root as [2, 122, 82, 176, 42, 188, 109, 24, 7, 173, 215, 152, 64, 62, 47, 36, 218, 23, 61, 147, 223, 20, 243, 56, 26, 241, 99, 56, 93, 1, 44, 169]. But in fn generate_prrof I am getting it as [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

**Comment by arnaucube** [comment]
Right, was not storing the current Root value in the db. Now each MerkleTree modification saves the current Root, and on opening a MerkleTree gets the Root from the db if was saved.
I've updated this repo & the crate package, should be working now

**Comment by Alakazam03** [comment]
Hi, thanks. It is working smooth.
 I get thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "node already exists"', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

I am trying to call the function again to add another TestValue to the tree. If I am trying to add two values sequentially then it is happening.
I went through lib.rs and got why is that coming. But how to handle and add another value to the tree.

**Comment by arnaucube** [comment]
In theory this error is returned when trying to add a leaf that has a collision with an already existing node, its possible that you are adding same value twice?

**Comment by Alakazam03** [comment]
`pub fn check_user_pref(user_preference : Json<UserPreference>, user_id : String) -> String {
    let user_preference : UserPreference = user_preference.into_inner();
    
        let mut sto = db::Db::new(user_id.to_string(), false);
        let mut mt = MerkleTree::new(&mut sto, 140 as u32);
        
        let user_preference_rtm : String = user_preference.get_string();
        let val: TestValue = TestValue {
            bytes: user_preference_rtm.as_bytes().to_vec(),
            index_length: 10,
        };
        mt.add(&val).unwrap();
        println!("{:?}", mt.get_root());
}`

I am calling the function twice but with different arguments. Although, user_id is same for both the call.

**Comment by Alakazam03** [comment]
`pub fn check_user_pref(user_preference : Json, user_id : String) -> String {
let user_preference : UserPreference = user_preference.into_inner();

    let mut sto = db::Db::new(user_id.to_string(), false);
    let mut mt = MerkleTree::new(&mut sto, 140 as u32);
    
    let user_preference_rtm : String = user_preference.get_string();
    let val: TestValue = TestValue {
        bytes: user_preference_rtm.as_bytes().to_vec(),
        index_length: 10,
    };
    mt.add(&val).unwrap();
    println!("{:?}", mt.get_root());
}`

I am calling the function twice but with different arguments. Although, user_id is same for both the call.

@arnaucube

**Comment by arnaucube** [comment]
which data are you putting into the `bytes` param of the `TestValue` struct?
One possible case could be that the first 10 bytes of the `bytes` param, are the same in both cases, and in the `index_length` you specify that is 10. The `index_length` specifies the length of the first bytes used to calculate the position of the leaf in the merkletree, so could be a possibility to add 2 different values into the merkletree, which the first 10 bytes are the same (but the rest are different), so in that case the position for both leafs would be the same in the tree, and when adding the 2nd value will return a collision error.

As an example, this is how the data of the leaf is structured:
```
|                           bytes                           |
|------[index_length]------|---[bytes.len()-index_length]---|
|  used for leaf position  |      used for leaf hash        |
```
In this way, the dev can use part of the leaf to determine its position in the tree, and part of the leaf value can be modified without afecting the position. This can be useful for example when you have a leaf with `user_id` and `user_description` for example, if the `index_length` is the `user_id` length, then the leafs position will be determined only by the `user_id`, so when you want to search a leaf, you will only need to know the `user_id` and you will find the position in the tree of the leaf, and you can get the rest of the leaf (the `user_description`), and merkleproof, etc

**Comment by Alakazam03** [comment]
Thanks a lot.
